Docker queries
ne-grebe/ToDo pull request #9
Opened 2022-02-18 14:25 UTC by ne-grebe

2022-02-18 15:01 UTC, lawhorkl requested changes

2022-02-18 15:01 UTC, lawhorkl commented on models/index.js
> +
Somehow compliled JS made it into your PR

2022-02-18 15:01 UTC, lawhorkl commented on src/Repositories/TodoRepository.ts
> +        return postTodoRemovalList
Why the added layer between Sequelize and the repo?

2022-02-18 15:13 UTC, ne-grebe commented on models/index.js
> +
pretty sure this was autogenerated when I started sequelize; my stuff works without this file

2022-02-18 15:30 UTC, ne-grebe commented on src/Repositories/TodoRepository.ts
> +        return postTodoRemovalList
I was getting some error with the interfaces in TodoRepository.ts a few days ago whenever I tried to establish a connection in that file... But I just tried to combine them now and it works just fine.

2022-02-23 15:55 UTC, lawhorkl approved these changes
Good job.

2022-02-23 15:55 UTC, lawhorkl commented on src/Repositories/TodoRepository.ts
> +            )`)
I left comments about this on Chase's PR as well.

Allowing user input directly into SQL queries is very dangerous and makes you vulnerable to a [SQL injection](https://www.w3schools.com/sql/sql_injection.asp) attack.

You can get around this vulnerability by [sanitizing](https://www.quora.com/What-exactly-is-data-sanitization-with-respect-to-SQL-injection) user input in all cases.

From my reading the best practice way to do this with Hapi is through either [replacements](https://sequelize.org/v7/manual/raw-queries.html#replacements) or [bind parameters](https://sequelize.org/v7/manual/raw-queries.html#bind-parameter)

2022-02-23 15:55 UTC, lawhorkl commented on src/Repositories/TodoRepository.ts
>      }
good job on recognizing that this doesn't need to be two functions

2022-02-23 15:55 UTC, lawhorkl commented on src/Repositories/TodoRepository.ts
> +            )`)
Fully preventing SQL injection attacks are also out of scope for this training this is primarily meant as an FYI in the future

2022-02-23 16:08 UTC, merged